function showMessage(el, text, ok=true){if(!el)return;el.textContent=text;el.className="form-message "+(ok?"success":"error")}
function formDataObject(form){return Object.fromEntries(new FormData(form).entries())}
function setupForm(id,msgId,key,label){const f=document.getElementById(id);if(!f)return;f.addEventListener("submit",e=>{e.preventDefault();if(!f.checkValidity()){showMessage(document.getElementById(msgId),"Please fill all required fields correctly.",false);f.reportValidity();return}const data=formDataObject(f);data.date=new Date().toLocaleString();const arr=(()=>{try{return JSON.parse(localStorage.getItem(key))||[]}catch(e){return[]}})();arr.push(data);localStorage.setItem(key,JSON.stringify(arr));increment("hc_total_forms");if(key==="hc_donations")increment("hc_donation_count");if(key==="hc_volunteers")increment("hc_volunteer_count");saveActivity(label+" submitted by "+(data.name||"visitor"));showMessage(document.getElementById(msgId),"Thank you! Your "+label.toLowerCase()+" was recorded successfully on this device.",true);f.reset();})}
setupForm("donationForm","donationMessage","hc_donations","Donation request");
setupForm("volunteerForm","volunteerMessage","hc_volunteers","Volunteer application");
setupForm("contactForm","contactMessage","hc_contacts","Contact message");

document.querySelectorAll(".amount-btn").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".amount-btn").forEach(b=>b.classList.remove("active"));btn.classList.add("active");document.getElementById("donationAmount").value=btn.dataset.amount}));

if(document.getElementById("liveTime")){const update=()=>{const d=new Date();document.getElementById("liveDate").textContent=d.toLocaleDateString(undefined,{day:"2-digit",month:"short",year:"numeric"});document.getElementById("liveTime").textContent=d.toLocaleTimeString();document.getElementById("connection").textContent=navigator.onLine?"Online":"Offline";document.getElementById("deviceType").textContent=/Mobi|Android|iPhone/i.test(navigator.userAgent)?"Mobile":"Desktop";document.getElementById("browserType").textContent=/Edg/i.test(navigator.userAgent)?"Edge":/Chrome/i.test(navigator.userAgent)?"Chrome":/Firefox/i.test(navigator.userAgent)?"Firefox":/Safari/i.test(navigator.userAgent)?"Safari":"Other";document.getElementById("screenSize").textContent=screen.width+" × "+screen.height;document.getElementById("pageViews").textContent=sessionStorage.getItem("hc_views")||"0";document.getElementById("formSubmissions").textContent=localStorage.getItem("hc_total_forms")||"0";document.getElementById("donationCount").textContent=localStorage.getItem("hc_donation_count")||"0";document.getElementById("volunteerCount").textContent=localStorage.getItem("hc_volunteer_count")||"0";const list=document.getElementById("activityList"),arr=getJSON("hc_activity",[]);list.innerHTML=arr.length?arr.slice(0,10).map(x=>`<div class="activity-item"><strong>${x.text}</strong><br><small>${x.time}</small></div>`).join(""):'<p class="empty">No activity recorded yet.</p>'};update();setInterval(update,1000);window.addEventListener("online",update);window.addEventListener("offline",update);document.getElementById("clearActivity").addEventListener("click",()=>{localStorage.removeItem("hc_activity");update()})}
